import React, { useState, useEffect } from 'react';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useSelector, useDispatch } from 'react-redux';
import {
  increment,
  decrement,
  incrementByAmount,
} from '../redux/slices/counterSlice';

import { loggedInOutToggle } from '../redux/slices/loggedSlice';

import { fetchUsers } from '../redux/slices/usersSlice';

import CardComponent from '../components/CardComponent';

export default function Home() {
  const users = useSelector((state) => state.users.users);
  const counter = useSelector((state) => state.counter.value);
  const logged = useSelector((state) => state.logged.logged);

  console.log('users', users);

  const dispatch = useDispatch();

  const handleIncrement = () => {
    dispatch(increment());
  };

  const handleDecrement = () => {
    dispatch(decrement());
  };

  const handleIncrementByAmount = () => {
    dispatch(incrementByAmount(5));
  };

  const handleLoginOut = () => {
    dispatch(loggedInOutToggle());
  };

  useEffect(() => {
    console.log('fetch try');
    dispatch(fetchUsers());
  }, [dispatch]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        <h1>Redux App</h1>
        <p>Counter: {counter} </p>
        <button onClick={handleIncrement}>Increment</button>
        <button onClick={handleDecrement}>Decrement</button>
        <button onClick={handleIncrementByAmount}>Increment By Amount</button>
        <div>
          <h1>Login</h1>
          {logged ? <p>Estas Logueado</p> : <p>No estas logueado</p>}
          <button onClick={handleLoginOut}>LogIn / LogOut</button>
        </div>
        <div>Users:</div>
        {users.map((users) => (
          <CardComponent key={users.id} data={users} />
        ))}
      </div>
    </div>
  );
}
